version: "3.9"

networks:
  stack_ponte:
    external: true

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jelly.${DOMAIN} #optional
    volumes:
      - ${VOLUMES}/jellyfin/config:/config
      - ${MEDIA}:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - stack_ponte
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jelly.rule=Host(`jelly.${DOMAIN}`)
      - traefik.http.services.jelly.loadbalancer.server.port=8096

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8091
    networks:
      - stack_ponte
    volumes:
      - ${VOLUMES}/qbittorrent/config:/config
      - ${MEDIA}/Dowloads:/downloads/
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8091:8091
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.qbt.rule=Host(`qbt.${DOMAIN}`)
      - traefik.http.services.qbt.loadbalancer.server.port=8091
