version: "3.9"

networks:
  stack_ponte:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${VOLUMES}/newhomeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123 #optional
    restart: unless-stopped
    privileged: true
    networks:
      - stack_ponte
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.home.rule=Host(`home.${DOMAIN}`)
      - traefik.http.services.home.loadbalancer.server.port=8123
      - "traefik.http.routers.home.tls.certresolver=le"

  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - stack_ponte
    ports:
      - 8484:80
      - 9443:443
    volumes:
      - ${NUVEM}/newnextcloud:/data
      - ${VOLUMES}/newnextcloud/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=newnextcloud
      - MYSQL_USER=root
      - MYSQL_HOST=${DATABASE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=8484
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
  # duplicati:
  #   image: ghcr.io/linuxserver/duplicati
  #   container_name: duplicati
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - CLI_ARGS= #optional
  #   volumes:
  #     - ${VOLUMES}/duplicati/config>:/config
  #     #- /home/alvitre/Developer/Pessoal/media_server/backup:/backups
  #     #- /home/alvitre/Developer/Pessoal/media_server/Media:/source
  #   ports:
  #     - 8200:8200
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - traefik.http.routers.duplicati.rule=Host(`duplicati.${DOMAIN}`)
  #     - traefik.http.services.duplicati.loadbalancer.server.port=8200
  #     - "traefik.http.routers.duplicati.tls.certresolver=le"
