version: "3.9"

networks:
  stack_ponte:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - stack_ponte
    ports:
      - 8097:8096
    volumes:
      - ${VOLUMES}/newjellyfin/config:/config
      - ${MEDIA}:/media
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jelly.rule=Host(`jelly.${DOMAIN}`)
      - traefik.http.services.jelly.loadbalancer.server.port=8096
      - JELLYFIN_PublishedServerUrl=https://jelly.${DOMAIN}
      - "traefik.http.routers.jelly.tls.certresolver=le"

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    networks:
      - stack_ponte
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USER} #optional
      - PASS=${PW} #optional
    volumes:
      - ${VOLUMES}/transmission/config:/config
      - ${MEDIA}/Dowloads:/downloads
      - ${MEDIA}/Watch:/watch
    ports:
      - 9092:9091
      - 51414:51413
      - 51414:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.qbt.rule=Host(`qbt.${DOMAIN}`)
      - traefik.http.services.qbt.loadbalancer.server.port=9091
      - "traefik.http.routers.qbt.tls.certresolver=le"
