version: "3.9"

networks:
  stack_ponte:
    external: true

services:

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${VOLUMES}/sonarr:/config
      - ${MEDIA}/Series:/tv
      - ${MEDIA}/Dowloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

  jackett:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${VOLUMES}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
      - traefik.http.services.jackett.loadbalancer.server.port=9696

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - stack_ponte
    ports:
      - 8097:8096
    volumes:
      - ${VOLUMES}/jellyfin/config:/config
      - ${MEDIA}:/media
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jelly.rule=Host(`jelly.${DOMAIN}`)
      - traefik.http.services.jelly.loadbalancer.server.port=8096
      - JELLYFIN_PublishedServerUrl=https://jelly.${DOMAIN}

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    networks:
      - stack_ponte
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USER} #optional
      - PASS=${PW} #optional
    volumes:
      - ${VOLUMES}/transmission/config:/config
      - ${MEDIA}/Dowloads:/downloads
      - ${MEDIA}/Watch:/watch
    ports:
      - 9092:9091
      - 51414:51413
      - 51414:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.qbt.rule=Host(`qbt.${DOMAIN}`)
      - traefik.http.services.qbt.loadbalancer.server.port=9091
