version: "3.9"

networks:
  stack_ponte:
    external: true

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    networks:
      - stack_ponte
    ports:
      - 8029:80
    user: 100:100
    volumes:
      - ${NUVEM}/officialnextcloud:/var/www/html/data
      - ${VOLUMES}/officialnextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_HOST=${DATABASE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - stack_ponte
    ports:
      - 8097:8096
    volumes:
      - ${VOLUMES}/jellyfin/config:/config
      - ${MEDIA}:/media
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jelly.rule=Host(`jelly.${DOMAIN}`)
      - traefik.http.services.jelly.loadbalancer.server.port=8096
      - JELLYFIN_PublishedServerUrl=https://jelly.${DOMAIN}

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    networks:
      - stack_ponte
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USER} #optional
      - PASS=${PW} #optional
    volumes:
      - ${VOLUMES}/transmission/config:/config
      - ${MEDIA}/Dowloads:/downloads
      - ${MEDIA}/Watch:/watch
    ports:
      - 9092:9091
      - 51414:51413
      - 51414:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.qbt.rule=Host(`qbt.${DOMAIN}`)
      - traefik.http.services.qbt.loadbalancer.server.port=9091
