version: "3"

networks:  
  stack_ponte:
    external: true

services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 5001:5000
    restart: unless-stopped

 
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - ${VOLUMES}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"
    privileged: true

    networks:
      - stack_ponte
      
  pyload:
    image: linuxserver/pyload-ng
    container_name: pyload
    restart: unless-stopped
    ports:
      - "8055:8000"
    volumes:
      - ${MEDIAS}/Downloads/complete:/downloads
      
      

