version: "3.9"

networks:
  internal:
    driver: bridge

# volumes:
#   dragon:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=192.168.15.5,id=1000,gid=1000,rw
#       device: ":/mnt"

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jelly.alvitre.com.br #optional
    volumes:
      - /net/dragon/mnt/RAID/iocage/files/sistemas/media_server/volumes/jellyfin/config:/config
      - /net/dragon/mnt/RAID/iocage/files/media/tv:/data/tvshows
      - /net/dragon/mnt/RAID/iocage/files/media/movies:/data/movies
      - /net/dragon/mnt/RAID/iocage/files/media/music:/data/music
      - /net/dragon/mnt/RAID/iocage/files/media/animes:/data/animes
      # -  ../media/movies/opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - internal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jelly.rule=Host(`jelly.alvitre.com.br`)
      - traefik.http.services.jelly.loadbalancer.server.port=8096

  sick:
    image: ghcr.io/linuxserver/sickchill
    container_name: sick
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /net/dragon/mnt/RAID/iocage/files/media/sick/config:/config
      - /net/dragon/mnt/RAID/iocage/files/media/sick/dowloads:/downloads
      - /net/dragon/mnt/RAID/iocage/files/media/sick/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8087
    volumes:
      - /net/dragon/mnt/RAID/iocage/files/sistemas/media_server/volumes/qbittorrent/config:/config
      - /net/dragon/mnt/RAID/iocage/files/media/dowloads:/config/downloads/
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8087:8087
    restart: unless-stopped

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    restart: always
    networks:
      - internal
    ports:
      - 8444:80
    volumes:
      - /net/dragon/mnt/RAID/iocage/files/next:/data
      - /net/dragon/mnt/RAID/iocage/files/nextconfig/nginx/site-confs:/config/nginx/site-confs
    environment:
      - PUID=1000
      - PGID=1000
      # - ADMIN_USERNAME=jorge
      # - ADMIN_PASSWORD=@1Sondeminas
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_HOST=mysql_${HOST}
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.alvitre.com.br`)
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
