version: "2"

networks:
  internal:
    driver: bridge

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jelly.alvitre.com.br #optional
    volumes:
      - /net/dragon/mnt/RAID/iocage/files/sistemas/media_server/volumes//jellyfin/config:/config
      - /net/dragon/mnt/RAID/iocage/files/media/tv:/data/tvshows
      - /net/dragon/mnt/RAID/iocage/files/media/movies:/data/movies
      - /net/dragon/mnt/RAID/iocage/files/media/music:/data/music
      # -  ../media/movies/opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - internal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.jelly.rule=Host(`jelly.alvitre.com.br`)
      - traefik.http.services.jelly.loadbalancer.server.port=8096