version: "3"

networks:
  stack_ponte:
    external: true

services:     
  pyload:
    image: linuxserver/pyload-ng
    container_name: pyload
    restart: unless-stopped
    ports:
      - "8055:8000"
    volumes:
      - ${MEDIAS}/Downloads/complete:/downloads
      
  jellyfin:
     image: jellyfin/jellyfin
     container_name: jellyfin
     user: 1000:100
     networks:
       - stack_ponte

     ports:
       - 8097:8096
     volumes:
       - ${VOLUMES}/jellyfin:/config
       - ${ENTRETENIMENTO}:/media
     restart: "unless-stopped"

  transmission:
     image: linuxserver/transmission
     container_name: transmission
     networks:
       - stack_ponte
     environment:
       - PUID=1000
       - PGID=100
       - TZ=${TZ}
       - USER=${USER}
       - PASS=${PW}
     volumes:

       - ${MEDIAS}/Downloads:/downloads
     ports:
       - 9092:9091
       - 51414:51413
       - 51414:51413/udp
     restart: unless-stopped
      

      

